### ISSUE TITLE
Feedback técnico

### ISSUE THREAD

**Issue by RuthSalvador** [maryisabel/lim-2018-05-bc-core-am-cipher#1]
# Recomendaciones de mejora 👍

- **`README.md`**: buena idea presentar a los usuarios y explicar la funcionalidad del proyecto. Puedes añadir como te organizaste durante estos 2 sprints, imágenes de la evolución de tu producto, las tecnologías que utilizaste.

- **`index.html`**: recuerda que debes validar tu `html`, te recomendamos revisar el enlace https://validator.w3.org/nu/?doc=https%3A%2F%2Fmaryisabel.github.io%2Flim-2018-05-bc-core-am-cipher%2Fsrc%2F  para mayor especificación. Te sugerimos utilizar más etiquetas semánticas como `header`, `section` o `footer`; en cuanto al nombre de tus `id` y `class` evita usar los nombres como boton1, boton2, etc; puedes usar la sintaxis con guiones en lugar de camelCase (éste se usa más para las variables en `javascript`). Ej:
  ``` js
  const textInput = document.getElementById('text-input');
  ```
  En cuanto al estilo del `html`, las propiedades y su valor van juntos, porque una etiqueta tiene diversas propiedades y si lo colocamos separados es difícil leerlo.

  **Evitar:**
  ```html
  <input type = " text " id = " text1 " placeholder = " Frase a cifrar ">
  ```

  **Recomendable:**
    ```html
  <input type="text" id="text-cipher" placeholder="Frase a cifrar" />
  ```

- **`cipher.js`**: buena lógica para las operaciones de cifrado y descifrado. Ten cuidado con tu indentación, debe ser de 2 espacios. Te recomendamos utilizar `for of` para utilizar la nueva sintaxis de `ES6`. Para la entrega final, te sugerimos colocar comentarios más concisos, evita dejar las especificaciones del proyecto.

- **`index.js`**: Buena idea declarar al inicio los elementos del DOM que utilizas.  Buen uso de `const`.  Recuerda declarar tus variables con nombres en inglés y descriptivas. Para la entrega final, te sugerimos colocar comentarios más concisos, evita colocarlo en cada línea, mejor usa uno por bloques/partes del código.

- **`style.css`**: recuerda utilizar clases descriptivas e inglés; te recomendamos crear clases, en lugar de usar `id` y etiquetas, para reutilizar estilos. Recuerda que tu página debe ser responsive, por lo tanto debe verse bien para diversos tamaños de pantalla.

- **Tests**: bien apuntar a una cobertura de 100%, recuerda que si deseas puedes agregar más tests para practicar.

Por último te recomendamos tener en cuenta la guía de estilos y utilizar comillas simples (' ') en archivos js y comillas dobles (" ") en el html. Además los usuarios pueden ver tu producto desde cualquier dispositivo.
Recuerda declarar tus variables, clases, id con nombres en inglés y descriptivas, así evitarás comentarios innecesarios; y cuidar tu indentación.
No te olvides llegar a los niveles esperados en Github.

Sigue así buen trabajo 👍

**Comment by maryisabel** [comment]
Hola Ruth, muchas gracias por tus recomendaciones, las tendré presentes, saludos.
